spring:
  application:
    name: instagram
  datasource:
    username: instagram_user
    password: instagram_password
    url: jdbc:mariadb://db:3306/instagram_db
    driver-class-name: org.mariadb.jdbc.Driver
  jpa.hibernate.ddl-auto: update
server:
  servlet:
    context-path: /api/v1
